services:
  cliproxyapi:
    image: eceasy/cli-proxy-api:latest
    container_name: cliproxyapi
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TZ: ${TZ}
      MANAGEMENT_PASSWORD: ${MANAGEMENT_PASSWORD}
      MANAGEMENT_STATIC_PATH: ${MANAGEMENT_STATIC_PATH}
      PGSTORE_LOCAL_PATH: ${PGSTORE_LOCAL_PATH}
      PGSTORE_DSN: ${PGSTORE_DSN}
#      HTTP_PROXY: ${HTTP_PROXY}
#      HTTPS_PROXY: ${HTTPS_PROXY}
#      NO_PROXY: ${NO_PROXY}
    ports:
      - "8317:8317"
    volumes:
      - ./cliproxyapi_data:/tmp
    networks:
      - cliproxyapi
      - apinetwork

  postgres:
    image: postgres:16-alpine
    container_name: cliproxyapi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    volumes:
      - ./cliproxyapi_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cliproxy -d cliproxy"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cliproxyapi

networks:
  cliproxyapi:
    name: cliproxyapi
  apinetwork:
    name: apinetwork
